### ISSUE TITLE
Not accepting any nickname

### ISSUE THREAD

**Issue by Danie10** [LubuWest/Friendiqa#4] opened 2018-04-01 13:05 UTC
I'm on Squeet.me with ID danie10 but the app rejects this, as well as full ID, my e-mail address etc. Is there something I'm missing on finding the correct nickname?

**Comment by LubuWest** [comment] 2018-04-04 15:41
What is the error message? If I put https://squeet.me in the Server field an danie10 in the nickname field I get no error message.

**Comment by Danie10** [comment] 2018-04-05 19:33
Ah OK it was that error as I was leaving the field. I see now if I just carried on it did go through so am logged din now. Tried to upload a photo of the error to my photo album on Friendica, but the mobile app does not drop down the list of photo albums and complains I must enter one. So I typed in manually there "Wall Photos" but it did not recognise it. But I'll check next release and play around with this version for now. Thanks for responding and clarifying.

**Comment by LubuWest** [comment] 2018-04-11 19:59
The issue is fixed in v0.2.1. I think you cannot upload directly to Wall Photos, you can attach to a message and all images from messages go automatically to Wall Photos. The list of albums is retrieved from the list of downloaded images.

**Closed** 2018-04-11 20:00 UTC
Labels: bug

**Comment by MarkusF47** [comment] 2018-08-21 07:11
I still have this issue with v0.3.1 from fdroid. I'm on a Galaxy A3(2017) with Android 8.0. Additionally, maybe related, the password field shows the password in plain text.

**Comment by LubuWest** [comment] 2018-08-25 21:12
I removed the check in 0.3.2. Can you check with current version?
